import { randomBytes } from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  FULL_MANIFEST,
  PINNED_DEV_DEPENDENCIES,
  type VeapDependencyManifest,
} from "./manifests.js";

/**
 * Post-scaffold mutations applied to the freshly generated
 * `create-next-app` project. Everything CNA generated is kept as-is - these
 * functions only inject what Veap needs on top of it.
 */

/** The dependency manifest applied to every generated project. */
export function getManifest(): VeapDependencyManifest {
  return FULL_MANIFEST;
}

/**
 * Removes the CNA-generated `app/` directory before the overlay is applied.
 * The overlay owns the whole `app/` tree: Next.js forbids a static page route
 * at the same specificity as an optional catch-all, so a leftover
 * `app/page.tsx` would conflict with the Veap `app/[[...catchAll]]/page.tsx`
 * ("You cannot define a route with the same specificity as an optional
 * catch-all route").
 */
export function clearAppDirectory(projectDir: string): void {
  const appDir = path.join(projectDir, "app");
  if (fs.existsSync(appDir)) {
    fs.rmSync(appDir, { recursive: true, force: true });
  }
}

/**
 * Merges the veap dependency manifest into the CNA-generated package.json.
 * CNA-provided entries (next, react, typescript, tailwind, eslint setup)
 * win for keys they already define; the manifest only fills the gaps and
 * overrides `@types/node` (Node >= 22 engine) plus adds `engines`.
 *
 * `packageName` overrides the generated package name (CNA derives it from
 * the folder, which loses the scope of names like `@scope/name`).
 */
export function injectVeapDependencies(
  projectDir: string,
  packageName?: string,
): void {
  const pkgPath = path.join(projectDir, "package.json");
  if (!fs.existsSync(pkgPath)) {
    throw new Error(`package.json not found in ${projectDir}`);
  }

  const pkg = JSON.parse(fs.readFileSync(pkgPath, "utf-8"));
  const manifest = getManifest();

  if (packageName) {
    pkg.name = packageName;
  }

  pkg.dependencies = {
    ...manifest.dependencies,
    ...pkg.dependencies,
  };
  pkg.devDependencies = {
    ...manifest.devDependencies,
    ...pkg.devDependencies,
    // Versions we own (node engine) win over CNA.
    ...PINNED_DEV_DEPENDENCIES,
  };
  if (manifest.scripts) {
    pkg.scripts = { ...pkg.scripts, ...manifest.scripts };
  }
  pkg.engines = { ...pkg.engines, node: ">=22" };

  fs.writeFileSync(pkgPath, `${JSON.stringify(pkg, null, 2)}\n`, "utf-8");
}

/**
 * Builds the starter `.env` content.
 *
 * ENCRYPTION_KEY is generated randomly per project (16 bytes, base64 - the
 * exact contract validated at boot by @veap/framework, which has no fallback
 * since the fail-fast fix). DATABASE_URL defaults to a local SQLite file;
 * mail values are left as documented placeholders.
 */
export function buildEnvFile(): string {
  const encryptionKey = randomBytes(16).toString("base64");

  return [
    "# Veap application configuration (generated by create-veap)",
    "",
    "# 16-byte base64 key used for AES encryption at rest (recovery codes,",
    "# TOTP secrets). Regenerate with: openssl rand -base64 16",
    `ENCRYPTION_KEY="${encryptionKey}"`,
    "",
    "# Local SQLite database (swap for a PostgreSQL URL in production)",
    'DATABASE_URL="sqlite:./storage/veap.sqlite"',
    "",
    "# Mail transport: smtp (default) | console | custom",
    "MAIL_TRANSPORT=smtp",
    "# MAIL_USERNAME=",
    "# MAIL_PASSWORD=",
    "# MAIL_FROM_ADDRESS=",
    "",
  ].join("\n");
}

/**
 * Writes the starter `.env`. CNA's generated `.gitignore` ignores `.env*`,
 * so the file stays local to the new project.
 */
export function writeEnvFile(projectDir: string): void {
  const envPath = path.join(projectDir, ".env");
  if (fs.existsSync(envPath)) {
    // Never clobber: CNA does not generate .env, so this only triggers on
    // re-runs over an existing directory.
    return;
  }
  fs.writeFileSync(envPath, buildEnvFile(), "utf-8");
}

/** Entries veap requires in `.gitignore` on top of CNA's output. */
const GITIGNORE_ENTRIES = ["public/storage/", "storage/", "**/*/dist"];

/**
 * Appends the missing veap entries (storage dirs, plugin dist) to the
 * CNA-generated `.gitignore`. Idempotent: no-op when everything is present.
 */
export function appendGitignore(projectDir: string): void {
  const gitignorePath = path.join(projectDir, ".gitignore");
  const existing = fs.existsSync(gitignorePath)
    ? fs.readFileSync(gitignorePath, "utf-8")
    : "";

  const present = new Set(existing.split("\n").map((line) => line.trim()));
  const missing = GITIGNORE_ENTRIES.filter((entry) => !present.has(entry));
  if (missing.length === 0) return;

  const block = [
    "",
    "# Veap additions (appended by create-veap)",
    ...missing,
    "",
  ].join("\n");

  const separator = existing.length > 0 && !existing.endsWith("\n") ? "\n" : "";

  fs.writeFileSync(gitignorePath, `${existing}${separator}${block}`, "utf-8");
}
